language: php
sudo: true
php:
  - 5.5

before_script:
  - /home/travis/.phpenv/versions/5.5/bin/composer self-update
  - /home/travis/.phpenv/versions/5.5/bin/composer install --prefer-dist

script: phpunit

notifications:
    on_success: never
    on_failure: never
