language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - apt-get install mcrypt php5-mcrypt
  - composer self-update

script: phpunit

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

sudo: true

notifications:
    on_success: never
    on_failure: always
