language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - sudo apt-get install mcrypt php5-mcrypt
  - sudo php5enmod mcrypt
  - sudo service apache2 restart

before_script:
  - /home/travis/.phpenv/versions/5.5/bin/composer self-update
  - /home/travis/.phpenv/versions/5.5/bin/composer install --prefer-dist

script: phpunit

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

sudo: true

notifications:
    on_success: never
    on_failure: always
